### ISSUE TITLE
Throw new Error('version_invalid: version bytes do not match any of the provided version(s)')

### ISSUE THREAD

**Issue by ay432** [jellicoe/EVERNODE_WITHDRAW#2]
Hello Everyone! node transfer_funds.js >> ./log.log
/home/EVERNODE_WITHDRAW/node_modules/ripple-address-codec/dist/xrp-codec.js:61
        throw new Error('version_invalid: version bytes do not match any of the provided version(s)');
        ^

Error: version_invalid: version bytes do not match any of the provided version(s)
    at Codec.decode (/home/EVERNODE_WITHDRAW/node_modules/ripple-address-codec/dist/xrp-codec.js:61:15)
    at Object.decodeSeed (/home/EVERNODE_WITHDRAW/node_modules/ripple-address-codec/dist/xrp-codec.js:139:33)
    at deriveKeypair (/home/EVERNODE_WITHDRAW/node_modules/ripple-keypairs/dist/index.js:89:34)
    at Object.familySeed (/home/EVERNODE_WITHDRAW/node_modules/xrpl-accountlib/dist/derive/familySeed.js:29:55)
    at Object.<anonymous> (/home/EVERNODE_WITHDRAW/transfer_funds.js:30:28)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)

Node.js v20.13.1
Please help me fix withdrawal script! Please explain what is rAddress and secret, where exactly it is coming from?

**Comment by jellicoe** [comment]
The rAddress is the xahaud address for your Evernode node - you can find this by running 

cat /etc/sashimono/mb-xrpl/mb-xrpl.cfg

the secret is the secret for what ever wallet (rAddress) you are using to sign the withdraw transaction

this could be your evernode node secret - to find this run (DO NOT PASTE it in the comments)

cat /home/sashimbxrpl/.evernode-host/.host-account-secret.key

or it could be the secret for your xaman account - depends if you set it as a 'regular key' or not 

read the readme again
